version: '3.8'
services:
  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=dsa2020
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
volumes:
  mysql:
    driver: local
  mongo:
    driver: local

